language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
notifications:
  flowdock:
    secure: qZQBHM1/DmyxLjWX1h9p/R+nhhBB9S2HYmnrrwhQZRETkDSMANKBAAsmBwrO6XdhxIZUIHWL7I3DtTw9vvZhN/SkcJstx8jwVJFycKN1bDlOGQN4e3MxbSRmLnB0i3/Gi4JaQ5C5Kd/EOJhhXncEJSujYHkg3EzYvj1c/oHQJTg=
