language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
notifications:
  flowdock:
    secure: fCuPZ13YwGzvVoCuJdjepV0vWc/3gwvqPlHmsap8I5tLfX5jpcXLr1fNHTYJ9qmgomnBpD/8GCjIPFimjuYNTZU4b8RAM7QkTyJmXicZZqAvdy7pmUNz1K0jBO87wsvCELwHnj17lRmMoKD2wR7MeEwjnZqL3SOrf3bTvRVBEeg=
